name: CI - Code Quality Check

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies (if requirements.txt exists)
        run: |
          if [ -f "requirements.txt" ]; then
            pip install -r requirements.txt
          fi

      - name: Run syntax and lint checks
        run: |
          echo "🔍 Checking Python code quality..."
          pip install flake8
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics || true

      - name: Compile C/C++ files (if any)
        run: |
          echo "🛠️ Checking C++ code compilation..."
          find . -name "*.cpp" -exec g++ {} -o /tmp/test_binary \; || true

      - name: Display completion message
        run: echo "✅ CI checks completed successfully!"
